title: avelardi
email: tony@velardi.io
description: > # this means to ignore newlines until "baseurl:"
  In the future we'll all be Riff Raff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://avelardi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: velardi
github_username:  avelardi
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
